// <auto-generated />
using C44_G03_EFCore03.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C44_G03_EFCore03.Migrations
{
    [DbContext(typeof(itiDbContext))]
    [Migration("20250829165534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("C44_G03_EFCore03.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("CourseDuration")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("CourseName");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseName")
                        .IsUnique();

                    b.HasIndex("TopicId");

                    b.ToTable("Courses", "dbo");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Course_Inst", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Evaluation")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Course_Insts", "dbo");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("DeptName");

                    b.HasKey("DeptId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments", "dbo");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("InstName");

                    b.Property<decimal>("InstructorSalary")
                        .HasColumnType("money");

                    b.HasKey("InstructorId");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.ToTable("Instructors", "dbo");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.StudCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("CourseGrade")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudCourses", "dbo");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("LastName");

                    b.Property<int>("StudentAge")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students", "dbo");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("TopicName");

                    b.HasKey("TopicId");

                    b.HasIndex("TopicName")
                        .IsUnique();

                    b.ToTable("Topics", "dbo");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Course", b =>
                {
                    b.HasOne("C44_G03_EFCore03.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Course_Inst", b =>
                {
                    b.HasOne("C44_G03_EFCore03.Models.Course", "Course")
                        .WithMany("Course_Insts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C44_G03_EFCore03.Models.Instructor", "Instructor")
                        .WithMany("Course_Insts")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Instructor", b =>
                {
                    b.HasOne("C44_G03_EFCore03.Models.Department", "Department")
                        .WithOne("HeadInstructor")
                        .HasForeignKey("C44_G03_EFCore03.Models.Instructor", "DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.StudCourse", b =>
                {
                    b.HasOne("C44_G03_EFCore03.Models.Course", "Course")
                        .WithMany("StudCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C44_G03_EFCore03.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Student", b =>
                {
                    b.HasOne("C44_G03_EFCore03.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Course", b =>
                {
                    b.Navigation("Course_Insts");

                    b.Navigation("StudCourses");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Department", b =>
                {
                    b.Navigation("HeadInstructor")
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("C44_G03_EFCore03.Models.Instructor", b =>
                {
                    b.Navigation("Course_Insts");
                });
#pragma warning restore 612, 618
        }
    }
}
